apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: LOOKER_BASE_URL
            value: ""
          - name: LOOKER_CLIENT_ID
            value: ""
            # valueFrom:
            #   secretKeyRef:
            #     name: looker-sdk
            #     key: client-id
          - name: LOOKER_CLIENT_SECRET
            value: ""
            # valueFrom:
            #   secretKeyRef:
            #     name: looker-sdk
            #     key: client-secret
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/lookml/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
        - name: build-lookml-datatest
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
